# Generated by Django 4.2.4 on 2023-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0007_remove_ride_passenger_ride_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='free_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
