# Generated by Django 4.2.4 on 2023-09-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0002_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
