# Generated by Django 4.2.4 on 2023-09-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0003_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_passenger', to='MeuApp.profile'),
        ),
    ]
