# Generated by Django 4.2.4 on 2023-09-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0005_alter_ride_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='free_seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
