# Generated by Django 4.2.4 on 2023-09-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0008_alter_ride_free_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={},
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='free_seats',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
