# Generated by Django 4.2.4 on 2023-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeuApp', '0009_alter_ride_options_alter_ride_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
